name: final_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #web_socket_channel: ^2.1.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  firebase_core: "^1.7.0"
  cloud_firestore: "^2.5.3"
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  math_expressions: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true